'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import {
  ArrowLeft, Sparkles, Send, Check, Save, MessageSquarePlus,
  StickyNote, ArrowRightLeft, Mail, Loader2, Building2, User,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { Textarea } from '../../../components/ui/textarea';
import { Skeleton } from '../../../components/ui/skeleton';
import { Separator } from '../../../components/ui/separator';
import { StageBadge, DraftStatusBadge, STAGE_ORDER, STAGE_META } from '../../../components/stage-badge';
import { cn } from '../../../lib/utils';

const ACTIVITY_ICONS = {
  note: StickyNote,
  stage_change: ArrowRightLeft,
  email_sent: Mail,
  ai_regenerate: Sparkles,
};

function timeAgo(iso) {
  if (!iso) return '';
  const s = (Date.now() - new Date(iso).getTime()) / 1000;
  if (s < 60) return 'just now';
  if (s < 3600) return `${Math.floor(s / 60)}m ago`;
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
  if (s < 604800) return `${Math.floor(s / 86400)}d ago`;
  return new Date(iso).toLocaleDateString();
}

export default function DealDetailPage() {
  const { id } = useParams();
  const [deal, setDeal] = useState(null);
  const [activities, setActivities] = useState(null);
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [note, setNote] = useState('');
  const [busy, setBusy] = useState('');
  const [flash, setFlash] = useState(null); // { kind: 'ok'|'err', text }
  const [loading, setLoading] = useState(true);

  const loadDeal = useCallback(async () => {
    const res = await fetch(`/api/deals/${id}`);
    if (!res.ok) return null;
    const data = await res.json();
    setDeal(data);
    setSubject(data.draft_subject || '');
    setBody(data.draft_body || '');
    return data;
  }, [id]);

  const loadActivities = useCallback(async () => {
    const res = await fetch(`/api/deals/${id}/activities`);
    if (res.ok) setActivities(await res.json());
  }, [id]);

  useEffect(() => {
    Promise.all([loadDeal(), loadActivities()]).finally(() => setLoading(false));
  }, [loadDeal, loadActivities]);

  async function action(name, fn) {
    setBusy(name);
    setFlash(null);
    try {
      await fn();
    } catch (err) {
      setFlash({ kind: 'err', text: err.message });
    } finally {
      setBusy('');
    }
  }

  async function expectOk(res, fallback) {
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error(data.error || fallback);
    }
    return res.json();
  }

  const saveDraft = () =>
    action('save', async () => {
      await expectOk(
        await fetch(`/api/deals/${id}/draft`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ subject, body }),
        }),
        'Failed to save draft'
      );
      setFlash({ kind: 'ok', text: 'Draft saved' });
      loadDeal();
    });

  const regenerate = () =>
    action('regenerate', async () => {
      const draft = await expectOk(
        await fetch(`/api/deals/${id}/regenerate`, { method: 'POST' }),
        'Failed to regenerate'
      );
      setSubject(draft.subject || '');
      setBody(draft.body || '');
      setFlash({ kind: 'ok', text: 'New draft generated by AI' });
      loadDeal();
      loadActivities();
    });

  const approve = () =>
    action('approve', async () => {
      // persist edits first so what gets approved is what's on screen
      if (deal.draft_id != null) {
        await expectOk(
          await fetch(`/api/deals/${id}/draft`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ subject, body }),
          }),
          'Failed to save draft before approving'
        );
      }
      await expectOk(
        await fetch(`/api/deals/${id}/approve`, { method: 'POST' }),
        'Failed to approve'
      );
      setFlash({ kind: 'ok', text: 'Draft approved' });
      loadDeal();
    });

  const send = () =>
    action('send', async () => {
      const data = await expectOk(
        await fetch(`/api/deals/${id}/send`, { method: 'POST' }),
        'Failed to send'
      );
      setFlash({ kind: 'ok', text: 'Marked as sent — opening your mail client' });
      loadDeal();
      loadActivities();
      window.location.href = data.mailto;
    });

  const addNote = () =>
    action('note', async () => {
      await expectOk(
        await fetch(`/api/deals/${id}/notes`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ content: note }),
        }),
        'Failed to add note'
      );
      setNote('');
      loadActivities();
    });

  const changeStage = (stage) =>
    action('stage', async () => {
      await expectOk(
        await fetch(`/api/deals/${id}/stage`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ stage }),
        }),
        'Failed to change stage'
      );
      loadDeal();
      loadActivities();
    });

  if (loading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-64" />
        <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
          <Skeleton className="h-[420px]" />
          <div className="space-y-5">
            <Skeleton className="h-40" />
            <Skeleton className="h-64" />
          </div>
        </div>
      </div>
    );
  }

  if (!deal) {
    return (
      <div className="py-16 text-center text-muted-foreground">
        Deal not found.{' '}
        <Link href="/" className="underline">Back to pipeline</Link>
      </div>
    );
  }

  const hasDraft = deal.draft_id != null;
  const regenerating = busy === 'regenerate';

  return (
    <>
      <Link
        href="/"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="h-4 w-4" /> Pipeline
      </Link>

      <div className="mb-5 flex flex-wrap items-center gap-3">
        <div className="mr-auto">
          <h1 className="text-xl font-bold tracking-tight">{deal.contact_name}</h1>
          <p className="text-sm text-muted-foreground">
            {deal.contact_title} · {deal.company_name}
          </p>
        </div>
        <StageBadge stage={deal.stage} />
        <select
          value={deal.stage}
          disabled={!!busy}
          onChange={(e) => changeStage(e.target.value)}
          className="h-9 rounded-md border border-input bg-card px-2.5 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        >
          {STAGE_ORDER.map((s) => (
            <option key={s} value={s}>Move to: {STAGE_META[s].label}</option>
          ))}
        </select>
      </div>

      {flash && (
        <div
          className={cn(
            'mb-4 rounded-md border px-3.5 py-2.5 text-sm',
            flash.kind === 'ok'
              ? 'border-emerald-200 bg-emerald-50 text-emerald-800'
              : 'border-red-200 bg-red-50 text-red-700'
          )}
        >
          {flash.text}
        </div>
      )}

      <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
        {/* ------------------------------ draft ------------------------------ */}
        <Card>
          <CardHeader className="flex-row items-center justify-between space-y-0">
            <CardTitle className="text-base">Email draft</CardTitle>
            <div className="flex items-center gap-2">
              <DraftStatusBadge status={deal.draft_status} />
              {deal.draft_edited_at && (
                <span className="text-xs text-muted-foreground">edited {timeAgo(deal.draft_edited_at)}</span>
              )}
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {regenerating ? (
              <div className="space-y-3">
                <Skeleton className="h-9 w-full" />
                <Skeleton className="h-72 w-full" />
                <p className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" /> Claude is redrafting this email…
                </p>
              </div>
            ) : !hasDraft ? (
              <div className="rounded-lg border border-dashed py-10 text-center">
                <p className="text-sm text-muted-foreground">No email has been drafted for this deal yet.</p>
                <Button className="mt-4" onClick={regenerate} disabled={!!busy}>
                  <Sparkles /> Generate with AI
                </Button>
              </div>
            ) : (
              <>
                <div className="space-y-1.5">
                  <label htmlFor="subject" className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Subject
                  </label>
                  <Input id="subject" value={subject} onChange={(e) => setSubject(e.target.value)} />
                </div>
                <div className="space-y-1.5">
                  <label htmlFor="body" className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    Body
                  </label>
                  <Textarea
                    id="body"
                    value={body}
                    onChange={(e) => setBody(e.target.value)}
                    className="min-h-[320px] leading-relaxed"
                  />
                </div>
                <div className="flex flex-wrap gap-2 pt-1">
                  <Button variant="outline" onClick={saveDraft} disabled={!!busy}>
                    {busy === 'save' ? <Loader2 className="animate-spin" /> : <Save />} Save
                  </Button>
                  <Button variant="outline" onClick={regenerate} disabled={!!busy}>
                    <Sparkles /> Regenerate with AI
                  </Button>
                  <Button onClick={approve} disabled={!!busy || deal.draft_status === 'sent'}>
                    {busy === 'approve' ? <Loader2 className="animate-spin" /> : <Check />} Approve
                  </Button>
                  <Button
                    variant="success"
                    onClick={send}
                    disabled={!!busy || deal.draft_status !== 'approved'}
                    title={deal.draft_status !== 'approved' ? 'Approve the draft before sending' : undefined}
                  >
                    {busy === 'send' ? <Loader2 className="animate-spin" /> : <Send />} Send
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* --------------------------- right column -------------------------- */}
        <div className="space-y-5">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm">
              <div className="flex items-start gap-2.5">
                <User className="mt-0.5 h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="font-medium">{deal.contact_name}</p>
                  <p className="text-muted-foreground">{deal.contact_title || '—'}</p>
                  {deal.contact_email ? (
                    <a href={`mailto:${deal.contact_email}`} className="text-blue-600 hover:underline">
                      {deal.contact_email}
                    </a>
                  ) : (
                    <p className="text-muted-foreground">no email on file</p>
                  )}
                  {deal.contact_linkedin_url && (
                    <a
                      href={deal.contact_linkedin_url}
                      target="_blank"
                      rel="noreferrer"
                      className="block truncate text-blue-600 hover:underline"
                    >
                      LinkedIn profile
                    </a>
                  )}
                </div>
              </div>
              <Separator />
              <div className="flex items-start gap-2.5">
                <Building2 className="mt-0.5 h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="font-medium">{deal.company_name}</p>
                  <p className="text-muted-foreground">{deal.industry || '—'}</p>
                </div>
              </div>
              <Separator />
              <div className="grid grid-cols-2 gap-2 text-sm">
                <div>
                  <p className="text-xs uppercase tracking-wide text-muted-foreground">Score</p>
                  <p className="font-semibold tabular-nums">{deal.score ?? '—'}</p>
                </div>
                <div>
                  <p className="text-xs uppercase tracking-wide text-muted-foreground">Source</p>
                  <p className="font-semibold">{deal.source || '—'}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-base">Notes & activity</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Textarea
                  placeholder="Add a note…"
                  value={note}
                  onChange={(e) => setNote(e.target.value)}
                  className="min-h-[70px]"
                />
                <Button size="sm" variant="outline" onClick={addNote} disabled={!!busy || !note.trim()}>
                  {busy === 'note' ? <Loader2 className="animate-spin" /> : <MessageSquarePlus />} Add note
                </Button>
              </div>
              <Separator />
              {activities === null ? (
                <div className="space-y-2">
                  <Skeleton className="h-10" />
                  <Skeleton className="h-10" />
                </div>
              ) : activities.length === 0 ? (
                <div className="rounded-lg border border-dashed py-8 text-center">
                  <p className="text-sm text-muted-foreground">No activity yet.</p>
                  <p className="mt-1 text-xs text-muted-foreground/70">
                    Notes, stage changes, sends and AI redrafts will show up here.
                  </p>
                </div>
              ) : (
                <ol className="space-y-3">
                  {activities.map((a) => {
                    const Icon = ACTIVITY_ICONS[a.type] || StickyNote;
                    return (
                      <li key={a.id} className="flex gap-2.5">
                        <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-secondary">
                          <Icon className="h-3.5 w-3.5 text-muted-foreground" />
                        </span>
                        <div className="min-w-0">
                          <p className="text-sm leading-snug">{a.content}</p>
                          <p className="mt-0.5 text-xs text-muted-foreground">
                            {a.type.replace('_', ' ')} · {timeAgo(a.created_at)}
                          </p>
                        </div>
                      </li>
                    );
                  })}
                </ol>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}
